version: '3.2'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
    - 9090:9090
    restart: always
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    - --web.config.file=/etc/prometheus/web.yml
    volumes:
    - ./prometheus/:/etc/prometheus/:ro
    - prometheusdata:/prometheus
    depends_on:
    - cadvisor
    - node-exporter

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    expose:
      - 8080
    restart: always
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
    - docker-exporter

  docker-exporter:
    image: rebel028/docker_exporter
    #image: prom/container-exporter 
    container_name: docker_exporter
    restart: always
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    expose:
      - 9417
        #- 9104
    environment:
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
  
  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node-exporter
    command:
      - '--path.rootfs=/host'
    #network_mode: host
    pid: host
    restart: always
    expose:
      - 9100
    volumes:
      - '/:/host:ro,rslave'

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.81.0
    container_name: otel-collector
    command: [ "--config=/etc/collector.yaml" ]
    # ports:
    #   - "4317:4317" # Connection from app to grafana tempo
    volumes:
      - ./otel/otel-collector-config.yml:/etc/collector.yaml
    # networks:
    #   - mynetwork

volumes:
  prometheusdata: