receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  logging:
    loglevel: info
  otlp:
    endpoint: ${OTEL_GRPC_ENDPOINT}
    headers:
      authorization: ${OTEL_AUTH_HEADER}
    tls:
      insecure: false

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging, otlp]