receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  logging:
    loglevel: info
  otlp:
    endpoint: grpc.example.com:443
    headers:
      authorization: Basic <Base64>
    tls:
      insecure: false

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging, otlp]